name: Makefile CI

on:
  push:
    branches: [ "UJC201-M0-V1.0.09R5-240523_1418" ]
  pull_request:
    branches: [ "UJC201-M0-V1.0.09R5-240523_1418" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
